export const CLASSNAME_VARIABLE = '$CLASSNAME';
export const TAB_CONTENT_VARIABLE = '$TAB_CONTENT';
export const TAB_VARIABLES_VARIABLE = '$TAB_VARIABLES';
export const TABS_IMPORTSTATEMENT_VARIABLE = '$TABS_IMPORTSTATEMENT';
export const FILENAME_VARIABLE = '$FILENAME';
export const PIPENAME_VARIABLE = '$PIPENAME';
export const SUPPLIEDNAME_VARIABLE = '$SUPPLIEDNAME';
export const IMPORTSTATEMENT_VARIABLE = '$IMPORTSTATEMENT';
export const IONICPAGE_VARIABLE = '$IONICPAGE';
export const KNOWN_FILE_EXTENSION = '.tmpl';

export const SPEC_FILE_EXTENSION = 'spec.ts';
export const NG_MODULE_FILE_EXTENSION = 'module.ts';

